### PR TITLE
#13: implement tool commandlet for aws cli

### LINKED ISSUE #13: Implement ToolCommandlet for AWS CLI
Create `ToolCommandlet` for AWS CLI
Old commandlet:
https://github.com/devonfw/ide/blob/master/scripts/src/main/resources/scripts/command/aws

### PR DESCRIPTION
**Pull request by MattesMrzik**
resolves #13: The ToolCommandlet for AWS CLI was implemented. Still has a workaround that manually grants executable permissions to the binary under linux. This workaround can be removed if issue #132 is fixed. 
This has already PR https://github.com/devonfw/IDEasy/pull/140 merged into, since this tool builds upon features from this PR. So probably merge first https://github.com/devonfw/IDEasy/pull/140, and then this one here.

Unrelated to the issue #13: Added `@TempDir Path tempDir` in `testSave` of `EnvironmentVariablesPropertiesFileTest`

### CODE REVIEW

File: cli/src/main/java/com/devonfw/tools/ide/tool/aws/Aws.java [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+import com.devonfw.tools.ide.context.IdeContext;
+import com.devonfw.tools.ide.environment.EnvironmentVariables;
+import com.devonfw.tools.ide.environment.EnvironmentVariablesType;
+import com.devonfw.tools.ide.process.ProcessContext;
+import com.devonfw.tools.ide.tool.ToolCommandlet;
+
+import static com.devonfw.tools.ide.os.OperatingSystem.LINUX;
+
+/**
+ * {@link ToolCommandlet} for AWS CLI (aws).
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/tool/aws/Aws.java:17]: we started the best practice to link to the tools homepage from the JavaDoc.

File: cli/src/main/java/com/devonfw/tools/ide/tool/aws/Aws.java [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+      } catch (IOException e) {
+        throw new CliException(
+            "Failed to get real path of " + installToolPath.resolve("aws") + " for making it executable.");
+      }
+      pc.addArgs("+x", realPathOfBinary.toString());
+      pc.run();
+
+      this.context.getFileAccess().delete(linuxInstallScript);
+      this.context.getFileAccess().delete(installToolPath.resolve("dist"));
+    }
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/tool/aws/Aws.java:59]: Great that you are testing for and considering all platforms.
However, we distinguish local and global tools. For global tools, we just download and run an installer.
However, for local tools already the installation logic shall create the proper installation.
It is still great to reuse our existing code and logic to download and extract tools but IMHO this is the proper place and way to solve it:
Here on linux the actual generic installation process with complete but only have an "installed" in `software/aws` and also create a `.ide.tool.version`. Therefore if the post installation fails, it will never recover from its inconsistent state.
Even worse the installer has already installed in the software repository and your post installation logic is somehow "in-situ" manipulating this result. Therefore when installing version X then installing Y and then installing version X again will result in symlinking the previous X version from the software repository where post install has already run on. So IMHO this will lead to a dead end and will never get stable and free of bugs.

Instead if we can not get a proper installation package for linux, we have to hook in way earlier.
Instead of moving the extracted contents to `$IDE_ROOT/software/default/aws/aws/«version»` we have to there run the installer to do the installation and write it there.

I am unsure if `aws` is the only commandlet where we have such problem.
If there are multiple such commandlets, we should create some more generic and reusable approach in the super-class hierarchy to make this happen easily in the commandlets. This somehow conflicts with #47 that is still WIP and not yet completed and merged. So feel invited to exchange with @salimbouch about this and PR #113.

**Review by hohwille — COMMENTED** [review]
@MattesMrzik thanks for your PR. Already looks good 👍 
I have added some review comments to give some guidance and direction even though your PR is still in WIP/draft state.

File: cli/src/main/java/com/devonfw/tools/ide/tool/aws/Aws.java (hunk 2 above)
Comment (MattesMrzik) [reply cli/src/main/java/com/devonfw/tools/ide/tool/aws/Aws.java:59]: Thanks for the remark. I am thinking about adding an extra "if" clause to the `ToolCommandlet::extract() `method. For aws the `./install` script takes arguments `-i` as install dir path and `-b` the directory to store symlinks to executables. This might not be consistent across tools that are installed with their own script. So maybe instead of adding an extra "if" to `ToolCommandlet::extract()` Aws.java should overwrite this method.

Comment (MattesMrzik) [reply cli/src/main/java/com/devonfw/tools/ide/tool/aws/Aws.java]: I now added an extra method `moveAndProcessExtraction `to ToolCommandlet that moves the extraction content from the `tmp` dir to the `software` dir. Usually this is just a call to FileAccess.move, but in the case for `aws` where an install script has to be called (on linux), `moveAndProcessExtraction` also calls this script.

**Comment by MattesMrzik** [comment]
This as already PR #140 merged into, since this tool builds upon features from this PR. So probably merge #140 first, and then this one here.

File: cli/src/main/java/com/devonfw/tools/ide/tool/aws/Aws.java [hunk 3]
```diff
@@ -0,0 +1,97 @@
...
+      Path awsInDistPath = from.resolve("dist").resolve("aws");
+      Path awsCompleterInDistPath = from.resolve("dist").resolve("aws_completer");
+
+      // TODO this can be removed if issue #132 is fixed
+      makeExecutable(awsInDistPath);
+      makeExecutable(awsCompleterInDistPath);
+      // running the install-script that aws shipped
+      ProcessContext pc = this.context.newProcess();
+      Path linuxInstallScript = from.resolve("install");
+      pc.executable("bash");
```
Comment (salimbouch) [inline cli/src/main/java/com/devonfw/tools/ide/tool/aws/Aws.java:64]: There's no need to add `bash` as the executable to the processContext, you can directly pass the script as the executable. The processContext checks whether the passed executable is a script, if so it looks for git bash to run it there, see [processContext](https://github.com/devonfw/IDEasy/blob/489c8d6e6775d1f7be3e4b7dc591c12896f074d9/cli/src/main/java/com/devonfw/tools/ide/process/ProcessContextImpl.java#L100-L111)

**Review by salimbouch — COMMENTED** [review]
Looks good :) I added 2 comments that could make the code a little bit shorter.

File: cli/src/main/java/com/devonfw/tools/ide/tool/aws/Aws.java [hunk 4]
```diff
@@ -0,0 +1,97 @@
...
+      permissions.add(PosixFilePermission.OWNER_EXECUTE);
+      permissions.add(PosixFilePermission.OTHERS_EXECUTE);
+      Files.setPosixFilePermissions(file, permissions);
+    } catch (IOException e) {
+      throw new RuntimeException("Adding execution permission for Group, Owner and Others did not work for " + file, e);
+    }
+  }
+
+  @Override
+  protected void moveAndProcessExtraction(Path from, Path to) {
```
[the remark this answers is not in the document]
Comment (MattesMrzik) [reply cli/src/main/java/com/devonfw/tools/ide/tool/aws/Aws.java:49]: Thanks, thats a great suggestion.

File: cli/src/main/java/com/devonfw/tools/ide/tool/aws/Aws.java (hunk 3 above)
Comment (MattesMrzik) [reply cli/src/main/java/com/devonfw/tools/ide/tool/aws/Aws.java]: Ah, thanks. I implemented it.

Comment (salimbouch) [reply cli/src/main/java/com/devonfw/tools/ide/tool/aws/Aws.java]: Nice :) 
I can't resolve this conversation, could you do it?

**Review by salimbouch — APPROVED** [review]
Looks good. Great job 👍

**Comment by hohwille** [comment]
Should be merged after #139 has been merged.

File: cli/src/main/java/com/devonfw/tools/ide/tool/aws/Aws.java [hunk 5]
```diff
@@ -0,0 +1,99 @@
...
+      Path awsCompleterInDistPath = from.resolve("dist").resolve("aws_completer");
+      makeExecutable(awsInDistPath);
+      makeExecutable(awsCompleterInDistPath);
+
+      // running the install-script that aws shipped
+      ProcessContext pc = this.context.newProcess();
+      Path linuxInstallScript = from.resolve("install");
+      pc.executable(linuxInstallScript);
+      pc.addArgs("-i", from.toString(), "-b", from.toString());
+      pc.run();
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/tool/aws/Aws.java:64]: doesn't this require admin/root permissions? Maybe `sudo` required?

**Review by hohwille — APPROVED** [review]
@MattesMrzik great job. Looks good. Thanks for testing on Windows and Linux.
Thanks for the helpful comments. Thanks for improving the JUnits. 👍 

BTW: You are decreasing the coverage by 0.3%. Pretty much noting but the current strict setup that @moritzLanger has created, prevents merging. So far I like this setup as it enforces us to continuously increase the coverage. However, we could discuss in the team meetings if we want to accept PRs with lets say `coverage delta > -0.5%`...
To get this merged faster, could you please add a little JUnit test method to increase coverage a very little?

File: cli/src/main/java/com/devonfw/tools/ide/tool/aws/Aws.java (hunk 5 above)
Comment (hohwille) [reply cli/src/main/java/com/devonfw/tools/ide/tool/aws/Aws.java:64]: most probably not as you are passing the `from` dir as installation target directory.
Shouldn't we install it in `to` dir and get rid of the sources or does it only work as a "in-situ" installation with a mix of source-code and compiled stuff?

Comment (MattesMrzik) [reply cli/src/main/java/com/devonfw/tools/ide/tool/aws/Aws.java:64]: I have tested it on Ubuntu 22 and it worked there without ever asking for the sudo pw.

Comment (MattesMrzik) [reply cli/src/main/java/com/devonfw/tools/ide/tool/aws/Aws.java:64]: > Here on linux the actual generic installation process is "completed" but only has an "installer" in software/aws and also created a .ide.tool.version. Therefore if the post installation fails, it will never recover from its inconsistent state.
Even worse the installer has already installed in the software repository and your post installation logic is somehow "in-situ" manipulating this result. Therefore when installing version X then installing Y and then installing version X again will result in symlinking the previous X version from the software repository where post install has already run on. So IMHO this will lead to a dead end and will never get stable and free of bugs.

You mentioned this in a previous comment. So I would install it to `from`, then create the symlinks, and after everything is done and has completed without error, move it to `to`.

**Review by hohwille — COMMENTED** [review]
@MattesMrzik sorry - I had a review comment that was pending and I forgot to submit it.
Can you please have a look?

I just rebased the PR and resolved merge conflicts so apart from the last comment we can merge.

File: cli/src/main/java/com/devonfw/tools/ide/tool/aws/Aws.java [hunk 6]
```diff
@@ -0,0 +1,99 @@
...
+public class Aws extends LocalToolCommandlet {
+
+  /**
+   * The constructor.
+   *
+   * @param context the {@link IdeContext}.
+   */
+  public Aws(IdeContext context) {
+
+    super(context, "aws", Set.of(TAG_CLOUD));
```
Comment (hohwille) [inline cli/src/main/java/com/devonfw/tools/ide/tool/aws/Aws.java:30]:
```suggestion
    super(context, "aws", Set.of(Tag.CLOUD));
```

Build failed after merge:
```
[ERROR] /home/runner/work/IDEasy/IDEasy/cli/src/main/java/com/devonfw/tools/ide/tool/aws/Aws.java:[30,33] error: cannot find symbol
  symbol:   variable TAG_CLOUD
  location: class Aws
```

File: cli/src/main/java/com/devonfw/tools/ide/common/SystemPath.java [hunk 7]
```diff
@@ -166,6 +166,7 @@ public Path getPath(String tool) {
    */
   public void setPath(String tool, Path path) {
 
+    this.paths.add(path);
```
[the remark this answers is not in the document]
Comment (MattesMrzik) [reply cli/src/main/java/com/devonfw/tools/ide/common/SystemPath.java]: Okey, I removed it.

**Review by hohwille — APPROVED** [review]
ready for merge 👍
